
import { Subject, DayName } from './types';

export const SUBJECT_COLORS: Record<string, string> = {
  'Arabic': '#059669', // emerald-600
  'Math': '#7c3aed', // violet-600
  'English': '#2563eb', // blue-600
  'Science': '#16a34a', // green-600
  'Social Studies': '#0284c7', // sky-600
  'ICT': '#475569', // slate-600
  'Religion': '#4f46e5', // indigo-600
  'Quran': '#d97706', // amber-500
};

export const DEFAULT_SUBJECTS: string[] = [
  'Arabic', 'English', 'Math', 'Science', 'Religion', 'Quran', 'Social Studies', 'ICT'
];

export const DEFAULT_GRADES = [
  'Grade 1', 'Grade 2', 'Grade 3', 'Grade 4', 'Grade 5', 'Grade 6',
  'Grade 7', 'Grade 8', 'Grade 9', 'Grade 10', 'Grade 11', 'Grade 12'
];

export const DAYS: DayName[] = ['Day 1', 'Day 2', 'Day 3', 'Day 4', 'Day 5'];

export const EMPTY_DAY_ENTRY = {
  period: 1,
  classwork: '',
  homework: '',
  items: '',
  tests: '',
  events: ''
};

export const MOCK_WEEKS = Array.from({ length: 40 }, (_, i) => ({
  weekNum: i + 1,
  label: `Week ${i + 1}`
}));

export const TRANSLATIONS = {
  en: {
    dashboard: "Dashboard",
    settings: "Settings",
    role: "Role",
    switch: "Switch",
    welcome: "Welcome back",
    selectSubject: "Select a subject to begin weekly planning.",
    completion: "Completion",
    activePlans: "Active Plans",
    weeklyOverview: "Weekly Completion Overview",
    planning: "Planning",
    editExport: "Edit and export your weekly schedule",
    save: "Save Plan",
    saved: "Saved!",
    export: "Export",
    exportPdf: "Export as PDF",
    exportExcel: "Export as Excel",
    exportMasterPdf: "Export Grade Master PDF",
    exportMasterExcel: "Export Grade Master Excel",
    masterPlan: "Master Weekly Plan",
    downloadMasterPdf: "Download Master PDF",
    downloadMasterExcel: "Download Master Excel",
    selectGrade: "Select Grade",
    selectWeek: "Select Week",
    grade: "Grade",
    week: "Week",
    from: "From",
    to: "To",
    day: "Day",
    classwork: "Classwork",
    homework: "Homework",
    items: "Items Required",
    tests: "Tests/Quizzes",
    events: "Events",
    typeHere: "Type here...",
    loading: "Loading planner...",
    version: "Version 1.0",
    assignedSubject: "Assigned Subject",
    readOnly: "Read Only",
    mySubject: "My Subject",
    viewOnlyMode: "View Only Mode",
    permissionMessage: "You are viewing this plan in read-only mode because it is not your assigned subject.",
    copyLink: "Copy Link",
    linkCopied: "Link Copied",
    adminLogin: "Admin Login",
    enterPassword: "Enter Admin Password",
    password: "Password",
    login: "Login",
    logout: "Logout",
    cancel: "Cancel",
    incorrectPassword: "Incorrect password",
    adminControls: "Admin Controls",
    announcement: "Global Announcement",
    announcementPlaceholder: "Type an announcement for all teachers...",
    postAnnouncement: "Post Announcement",
    dataManagement: "Data Management",
    backupData: "Backup Data",
    restoreData: "Restore Data",
    clearData: "Reset System",
    dangerZone: "Danger Zone",
    confirmReset: "Are you sure? This will delete ALL plans.",
    backupDesc: "Download a JSON file of all plans.",
    restoreDesc: "Upload a JSON backup file.",
    resetDesc: "Delete all local data.",
    restoreSuccess: "Data restored successfully!",
    restoreFail: "Failed to restore data.",
    teacherManagement: "Teacher Management",
    weeklyProgressReport: "Weekly Progress Report",
    subjectColumn: "Subject",
    actions: "Actions",
    schoolBranding: "School Branding",
    schoolName: "School Name",
    uploadLogo: "Upload Logo",
    removeLogo: "Remove Logo",
    logoSizeLimit: "Max size: 500KB (PNG/JPG)",
    systemConfig: "System Configuration",
    manageSubjects: "Manage Subjects",
    manageGrades: "Manage Grades",
    addSubject: "Add Subject",
    addGrade: "Add Grade",
    delete: "Delete",
    confirmDelete: "Are you sure?",
    add: "Add",
    subjects: {
      "Arabic": "Arabic",
      "Math": "Math",
      "English": "English",
      "Science": "Science",
      "Social Studies": "Social Studies",
      "Religion": "Religion",
      "Quran": "Quran",
      "ICT": "ICT"
    }
  },
  ar: {
    dashboard: "لوحة التحكم",
    settings: "الإعدادات",
    role: "الدور",
    switch: "تبديل",
    welcome: "مرحباً بك",
    selectSubject: "اختر مادة للبدء في التخطيط الأسبوعي.",
    completion: "الإنجاز",
    activePlans: "خطط نشطة",
    weeklyOverview: "نظرة عامة على الإنجاز الأسبوعي",
    planning: "تخطيط",
    editExport: "تعديل وتصدير جدولك الأسبوعي",
    save: "حفظ الخطة",
    saved: "تم الحفظ!",
    export: "تصدير",
    exportPdf: "تصدير PDF",
    exportExcel: "تصدير Excel",
    exportMasterPdf: "تصدير ملف شامل للصف (PDF)",
    exportMasterExcel: "تصدير ملف شامل للصف (Excel)",
    masterPlan: "الخطة الأسبوعية الشاملة",
    downloadMasterPdf: "تحميل ملف شامل PDF",
    downloadMasterExcel: "تحميل ملف شامل Excel",
    selectGrade: "اختر الصف",
    selectWeek: "اختر الأسبوع",
    grade: "الصف",
    week: "الأسبوع",
    from: "من",
    to: "إلى",
    day: "اليوم",
    classwork: "العمل الصفي",
    homework: "الواجب المنزلي",
    items: "المتطلبات",
    tests: "الاختبارات",
    events: "الفعاليات",
    typeHere: "اكتب هنا...",
    loading: "جاري التحميل...",
    version: "الإصدار 1.0",
    assignedSubject: "المادة المخصصة",
    readOnly: "للإطلاع فقط",
    mySubject: "مادتي",
    viewOnlyMode: "وضع القراءة فقط",
    permissionMessage: "أنت تشاهد هذه الخطة في وضع القراءة فقط لأنها ليست مادتك المخصصة.",
    copyLink: "نسخ الرابط",
    linkCopied: "تم النسخ",
    adminLogin: "دخول المسؤول",
    enterPassword: "أدخل كلمة مرور المسؤول",
    password: "كلمة المرور",
    login: "دخول",
    logout: "تسجيل خروج",
    cancel: "إلغاء",
    incorrectPassword: "كلمة المرور غير صحيحة",
    adminControls: "أدوات المسؤول",
    announcement: "إعلان عام",
    announcementPlaceholder: "اكتب إعلاناً لجميع المعلمين...",
    postAnnouncement: "نشر الإعلان",
    dataManagement: "إدارة البيانات",
    backupData: "نسخ احتياطي",
    restoreData: "استعادة البيانات",
    clearData: "إعادة ضبط النظام",
    dangerZone: "منطقة الخطر",
    confirmReset: "هل أنت متأكد؟ سيتم حذف جميع الخطط.",
    backupDesc: "تحميل ملف JSON لجميع الخطط.",
    restoreDesc: "رفع ملف نسخ احتياطي JSON.",
    resetDesc: "حذف جميع البيانات المحلية.",
    restoreSuccess: "تمت استعادة البيانات بنجاح!",
    restoreFail: "فشل استعادة البيانات.",
    teacherManagement: "إدارة المعلمين",
    weeklyProgressReport: "تقرير التقدم الأسبوعي",
    subjectColumn: "المادة",
    actions: "الإجراءات",
    schoolBranding: "هوية المدرسة",
    schoolName: "اسم المدرسة",
    uploadLogo: "رفع الشعار",
    removeLogo: "حذف الشعار",
    logoSizeLimit: "أقصى حجم: 500 ك.ب (PNG/JPG)",
    systemConfig: "إعدادات النظام",
    manageSubjects: "إدارة المواد",
    manageGrades: "إدارة الصفوف",
    addSubject: "إضافة مادة",
    addGrade: "إضافة صف",
    delete: "حذف",
    confirmDelete: "هل أنت متأكد؟",
    add: "إضافة",
    subjects: {
      "Arabic": "اللغة العربية",
      "Math": "الرياضيات",
      "English": "اللغة الإنجليزية",
      "Science": "العلوم",
      "Social Studies": "الدراسات الاجتماعية",
      "Religion": "التربية الدينية",
      "Quran": "القرآن الكريم",
      "ICT": "تكنولوجيا المعلومات"
    }
  }
};
